name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: ./gn32

      - name: Checkout batteries
        with:
          repository: 1bardesign/batteries
          path: ./batteries

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: 5.3

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup dependencies
        run: luarocks install ldoc

      - name: Run tests
        run: cd gn32 && make ci

      - name: Build docs
        run: cd gn32 && make docs

      - name: Upload artifact
        if: ${{ github.ref == "refs/heads/master" }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./gn32/docs

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == "refs/heads/master" }}
        id: deployment
        uses: actions/deploy-pages@v4
